/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprograii;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Danna Casco
 */
public class principal extends javax.swing.JFrame {

    private Color originalColor = null;

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        originalColor = jPanel2.getBackground();
        this.setLocationRelativeTo(null);
        registroP.setVisible(false);
        docentesP.setVisible(false);
        badLoginTXT.setVisible(false);
        this.setResizable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closeP = new javax.swing.JPanel();
        closeTXT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        ingresarBT = new javax.swing.JButton();
        badLoginTXT = new javax.swing.JLabel();
        forgotPassTXT = new javax.swing.JLabel();
        registroP = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        closeP1 = new javax.swing.JPanel();
        closeTXT1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        bienvenidaTXT = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        registrou1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        docentesP = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        closeP2 = new javax.swing.JPanel();
        closeTXT2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        modDP1 = new javax.swing.JPanel();
        modD = new javax.swing.JLabel();
        asignarDP1 = new javax.swing.JPanel();
        asignD = new javax.swing.JLabel();
        crearDP1 = new javax.swing.JPanel();
        addD = new javax.swing.JLabel();
        eliminarDP1 = new javax.swing.JPanel();
        deleteD = new javax.swing.JLabel();
        crearD1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        modD1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        eliminarD = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        asignarD = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(229, 226, 226));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portalf-removebg-preview.png"))); // NOI18N

        closeP.setBackground(new java.awt.Color(0, 51, 102));
        closeP.setForeground(new java.awt.Color(0, 0, 102));

        closeTXT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeTXT.setForeground(new java.awt.Color(255, 255, 255));
        closeTXT.setText("X");
        closeTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closePLayout = new javax.swing.GroupLayout(closeP);
        closeP.setLayout(closePLayout);
        closePLayout.setHorizontalGroup(
            closePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closePLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeTXT)
                .addContainerGap())
        );
        closePLayout.setVerticalGroup(
            closePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeTXT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(closeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 785, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Inicio de Sesion");

        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Accede a tu cuenta");

        userTF.setForeground(new java.awt.Color(231, 231, 231));
        userTF.setText("Ingrese nombre de usuario");
        userTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTFMousePressed(evt);
            }
        });

        passwordTF.setForeground(new java.awt.Color(225, 225, 225));
        passwordTF.setText("**********");
        passwordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTFMousePressed(evt);
            }
        });

        ingresarBT.setBackground(new java.awt.Color(0, 51, 102));
        ingresarBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ingresarBT.setForeground(new java.awt.Color(255, 255, 255));
        ingresarBT.setText("Ingresar\n");
        ingresarBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBTMouseClicked(evt);
            }
        });

        badLoginTXT.setForeground(new java.awt.Color(255, 0, 0));
        badLoginTXT.setText("usuario/contraseña incorrectos");
        badLoginTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        forgotPassTXT.setForeground(new java.awt.Color(0, 51, 102));
        forgotPassTXT.setText("¿olvidaste tu contraseña?");
        forgotPassTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(forgotPassTXT)
                    .addComponent(badLoginTXT)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(userTF, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(passwordTF)
                    .addComponent(ingresarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badLoginTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(forgotPassTXT)
                .addContainerGap())
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 183, -1, -1));

        registroP.setBackground(new java.awt.Color(229, 226, 226));
        registroP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        closeP1.setBackground(new java.awt.Color(0, 51, 102));
        closeP1.setForeground(new java.awt.Color(0, 0, 102));

        closeTXT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeTXT1.setForeground(new java.awt.Color(255, 255, 255));
        closeTXT1.setText("X");
        closeTXT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeTXT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeTXT1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeTXT1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeTXT1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeP1Layout = new javax.swing.GroupLayout(closeP1);
        closeP1.setLayout(closeP1Layout);
        closeP1Layout.setHorizontalGroup(
            closeP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeTXT1)
                .addContainerGap())
        );
        closeP1Layout.setVerticalGroup(
            closeP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeTXT1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo unitec (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(240, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(closeP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        registroP.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 785, 130));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        bienvenidaTXT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bienvenidaTXT.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bienvenidaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bienvenidaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        registroP.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 710, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        registrou1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registro.png"))); // NOI18N
        registrou1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrou1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrou1MouseClicked(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(0, 51, 153));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 102));
        jLabel25.setText("Registro");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(registrou1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(registrou1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(18, 18, 18))
        );

        registroP.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 208));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profesor.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(0, 51, 102));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 102));
        jLabel27.setText("Docentes");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        registroP.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, 210));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alumno.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 102));
        jLabel29.setText("Alumnos");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(14, 14, 14))
        );

        registroP.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 160, 208));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clase.png"))); // NOI18N
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 51, 102));
        jLabel31.setText("clases");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(17, 17, 17))
        );

        registroP.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 160, 210));

        docentesP.setBackground(new java.awt.Color(255, 255, 255));
        docentesP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        closeP2.setBackground(new java.awt.Color(0, 51, 102));
        closeP2.setForeground(new java.awt.Color(0, 0, 102));

        closeTXT2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeTXT2.setForeground(new java.awt.Color(255, 255, 255));
        closeTXT2.setText("X");
        closeTXT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeTXT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeTXT2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeTXT2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeTXT2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeP2Layout = new javax.swing.GroupLayout(closeP2);
        closeP2.setLayout(closeP2Layout);
        closeP2Layout.setHorizontalGroup(
            closeP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeP2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeTXT2)
                .addContainerGap())
        );
        closeP2Layout.setVerticalGroup(
            closeP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeTXT2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo unitec (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(245, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(closeP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        docentesP.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        modDP1.setBackground(new java.awt.Color(255, 255, 255));

        modD.setBackground(new java.awt.Color(0, 51, 102));
        modD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modD.setForeground(new java.awt.Color(0, 51, 102));
        modD.setText("Modificar Docente");
        modD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout modDP1Layout = new javax.swing.GroupLayout(modDP1);
        modDP1.setLayout(modDP1Layout);
        modDP1Layout.setHorizontalGroup(
            modDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modDP1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(modD)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        modDP1Layout.setVerticalGroup(
            modDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modD, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        docentesP.add(modDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        asignarDP1.setBackground(new java.awt.Color(255, 255, 255));

        asignD.setBackground(new java.awt.Color(0, 51, 102));
        asignD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        asignD.setForeground(new java.awt.Color(0, 51, 102));
        asignD.setText("Asignar Clase");
        asignD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarDP1Layout = new javax.swing.GroupLayout(asignarDP1);
        asignarDP1.setLayout(asignarDP1Layout);
        asignarDP1Layout.setHorizontalGroup(
            asignarDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignarDP1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(asignD)
                .addGap(19, 19, 19))
        );
        asignarDP1Layout.setVerticalGroup(
            asignarDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignarDP1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(asignD, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        docentesP.add(asignarDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        crearDP1.setBackground(new java.awt.Color(255, 255, 255));
        crearDP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearDP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearDP1MouseEntered(evt);
            }
        });

        addD.setBackground(new java.awt.Color(0, 51, 102));
        addD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addD.setForeground(new java.awt.Color(0, 51, 102));
        addD.setText("Agregar Docente");
        addD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout crearDP1Layout = new javax.swing.GroupLayout(crearDP1);
        crearDP1.setLayout(crearDP1Layout);
        crearDP1Layout.setHorizontalGroup(
            crearDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearDP1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addD)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        crearDP1Layout.setVerticalGroup(
            crearDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        docentesP.add(crearDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        eliminarDP1.setBackground(new java.awt.Color(255, 255, 255));

        deleteD.setBackground(new java.awt.Color(0, 51, 102));
        deleteD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteD.setForeground(new java.awt.Color(0, 51, 102));
        deleteD.setText("Eliminar Docente");
        deleteD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout eliminarDP1Layout = new javax.swing.GroupLayout(eliminarDP1);
        eliminarDP1.setLayout(eliminarDP1Layout);
        eliminarDP1Layout.setHorizontalGroup(
            eliminarDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarDP1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(deleteD)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        eliminarDP1Layout.setVerticalGroup(
            eliminarDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteD, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        docentesP.add(eliminarDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 51, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("Creación de Docente");

        jTextField7.setForeground(new java.awt.Color(204, 204, 204));
        jTextField7.setText("Nombre");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setForeground(new java.awt.Color(204, 204, 204));
        jTextField8.setText("Apellido");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setForeground(new java.awt.Color(204, 204, 204));
        jTextField9.setText("Profesión");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Sueldo:    ");

        jTextField10.setForeground(new java.awt.Color(204, 204, 204));
        jTextField10.setText("Ingrese  nombre de usuario");

        jTextField11.setForeground(new java.awt.Color(204, 204, 204));
        jTextField11.setText("ID");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new user.png"))); // NOI18N

        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear");

        javax.swing.GroupLayout crearD1Layout = new javax.swing.GroupLayout(crearD1);
        crearD1.setLayout(crearD1Layout);
        crearD1Layout.setHorizontalGroup(
            crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearD1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearD1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148)
                                .addComponent(jLabel21)
                                .addGap(72, 72, 72))
                            .addGroup(crearD1Layout.createSequentialGroup()
                                .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()))
                        .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(crearD1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearD1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(227, 227, 227))))
        );
        crearD1Layout.setVerticalGroup(
            crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearD1Layout.createSequentialGroup()
                .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearD1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(crearD1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(crearD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        docentesP.add(crearD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 580, 440));

        jLabel23.setBackground(new java.awt.Color(0, 51, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("Modificación de Docente");

        jTextField12.setForeground(new java.awt.Color(204, 204, 204));
        jTextField12.setText("Nombre");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setForeground(new java.awt.Color(204, 204, 204));
        jTextField13.setText("Apellido");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField14.setForeground(new java.awt.Color(204, 204, 204));
        jTextField14.setText("Profesión");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 153, 153));
        jLabel32.setText("Sueldo:    ");

        jTextField15.setForeground(new java.awt.Color(204, 204, 204));
        jTextField15.setText("Ingrese  nombre de usuario");

        jTextField16.setForeground(new java.awt.Color(204, 204, 204));
        jTextField16.setText("ID");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario (1).png"))); // NOI18N

        jPasswordField2.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField2.setText("jPasswordField1");

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modificar");

        javax.swing.GroupLayout modD1Layout = new javax.swing.GroupLayout(modD1);
        modD1.setLayout(modD1Layout);
        modD1Layout.setHorizontalGroup(
            modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modD1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modD1Layout.createSequentialGroup()
                        .addGroup(modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modD1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel8)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel24))
                            .addGroup(modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(modD1Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modD1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modD1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(196, 196, 196))))
        );
        modD1Layout.setVerticalGroup(
            modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modD1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );

        docentesP.add(modD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 440));

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete (1).png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Seleccione Docente a eliminar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout eliminarDLayout = new javax.swing.GroupLayout(eliminarD);
        eliminarD.setLayout(eliminarDLayout);
        eliminarDLayout.setHorizontalGroup(
            eliminarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarDLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(eliminarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(eliminarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarDLayout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(248, 248, 248))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarDLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)))))
            .addGroup(eliminarDLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarDLayout.setVerticalGroup(
            eliminarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarDLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(17, 17, 17))
        );

        docentesP.add(eliminarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 440));

        jLabel34.setBackground(new java.awt.Color(0, 51, 102));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 51, 102));
        jLabel34.setText("Asignación de clase");

        jButton4.setBackground(new java.awt.Color(0, 51, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Asignar");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asignar.png"))); // NOI18N

        jScrollPane3.setViewportView(jList3);

        jScrollPane4.setViewportView(jList4);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Clases Disponibles");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Clases Asignadas");

        javax.swing.GroupLayout asignarDLayout = new javax.swing.GroupLayout(asignarD);
        asignarD.setLayout(asignarDLayout);
        asignarDLayout.setHorizontalGroup(
            asignarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignarDLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(asignarDLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(asignarDLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignarDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(asignarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignarDLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignarDLayout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignarDLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))))
        );
        asignarDLayout.setVerticalGroup(
            asignarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignarDLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addGap(13, 13, 13)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(asignarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asignarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        docentesP.add(asignarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(docentesP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(registroP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(docentesP, javax.swing.GroupLayout.PREFERRED_SIZE, 494, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXTMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeTXTMouseClicked

    private void closeTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXTMouseEntered
        // TODO add your handling code here:
        closeP.setBackground(Color.GRAY);
    }//GEN-LAST:event_closeTXTMouseEntered

    private void closeTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXTMouseExited
        // TODO add your handling code here:
        closeP.setBackground(originalColor);
    }//GEN-LAST:event_closeTXTMouseExited

    private void userTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTFMousePressed
        // TODO add your handling code here:
        if (userTF.getText().equals("Ingrese nombre de usuario")) {
            userTF.setText("");
            userTF.setForeground(Color.BLACK);
        }
        if (String.valueOf(passwordTF.getPassword()).equals("")) {
            passwordTF.setText("****************");
            passwordTF.setForeground(Color.GRAY);

        }
    }//GEN-LAST:event_userTFMousePressed

    private void passwordTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTFMousePressed
        // TODO add your handling code here:

        if (String.valueOf(passwordTF.getPassword()).equals("**********")) {
            passwordTF.setText("");
            passwordTF.setForeground(Color.BLACK);
        }
        if (userTF.getText().equals("")) {
            userTF.setText("Ingrese nombre de usuario");
            userTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_passwordTFMousePressed

    private void ingresarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBTMouseClicked
        // TODO add your handling code here:
        String usuario = userTF.getText();
        String contraseña = String.valueOf(passwordTF.getPassword());
        String archivoUsuarios = "./usuarios.txt";
        String rol = "";
        String nombre = "";
        String apellido = "";

        try {
            boolean encontrado;
            try ( FileReader fr = new FileReader(archivoUsuarios);  BufferedReader br = new BufferedReader(fr)) {
                String linea;
                encontrado = false;
                while ((linea = br.readLine()) != null) {
                    var partes = linea.split("\\|");
                    String usuarioActual = partes[0];
                    String contraseñaActual = partes[1];
                    rol = partes[2];
                    nombre = partes[3];
                    apellido = partes[4];

                    if (usuarioActual.equals(usuario) && contraseñaActual.equals(contraseña)) {
                        encontrado = true;
                        break;
                    }
                }
            }

            if (encontrado) {
                switch (rol) {
                    case "registro" -> {
                        bg.setVisible(false);
                        docentesP.setVisible(false);
                        registroP.setVisible(true);
                        bienvenidaTXT.setText("¡Hola " + nombre + " " + apellido + "!");

                    }
                    case "alumno" -> {
                        bg.setVisible(false);
                        docentesP.setVisible(false);
                        registroP.setVisible(false);

                    }
                    case "docente" -> {
                        bg.setVisible(false);
                        registroP.setVisible(false);
                        docentesP.setVisible(false);

                    }
                    default -> {
                    }
                }
            } else {
                badLoginTXT.setVisible(true);
            }

        } catch (IOException e) {
        }
    }//GEN-LAST:event_ingresarBTMouseClicked

    private void closeTXT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXT1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeTXT1MouseClicked

    private void closeTXT1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXT1MouseEntered
        // TODO add your handling code here:
        closeP1.setBackground(Color.gray);
    }//GEN-LAST:event_closeTXT1MouseEntered

    private void closeTXT1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXT1MouseExited
        // TODO add your handling code here:
        closeP1.setBackground(originalColor);
    }//GEN-LAST:event_closeTXT1MouseExited

    private void registrou1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrou1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrou1MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        bg.setVisible(false);
        registroP.setVisible(false);
        modD1.setVisible(false);
        eliminarD.setVisible(false);
        asignarD.setVisible(false);
        docentesP.setVisible(true);
        crearD1.setVisible(true);

    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void closeTXT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXT2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeTXT2MouseClicked

    private void closeTXT2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXT2MouseEntered
        // TODO add your handling code here:
        closeP2.setBackground(Color.GRAY);
    }//GEN-LAST:event_closeTXT2MouseEntered

    private void closeTXT2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTXT2MouseExited
        // TODO add your handling code here:
        closeP2.setBackground(originalColor);
    }//GEN-LAST:event_closeTXT2MouseExited

    private void modDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDMouseEntered
        // TODO add your handling code here:
        modDP1.setBackground(originalColor);
        modD.setForeground(Color.WHITE);
    }//GEN-LAST:event_modDMouseEntered

    private void modDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDMouseExited
        // TODO add your handling code here:
        modDP1.setBackground(Color.WHITE);
        modD.setForeground(originalColor);
    }//GEN-LAST:event_modDMouseExited

    private void asignDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignDMouseEntered
        // TODO add your handling code here:
        asignarDP1.setBackground(originalColor);
        asignD.setForeground(Color.WHITE);
    }//GEN-LAST:event_asignDMouseEntered

    private void asignDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignDMouseExited
        // TODO add your handling code here:
        asignarDP1.setBackground(Color.WHITE);
        asignD.setForeground(originalColor);
    }//GEN-LAST:event_asignDMouseExited

    private void addDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDMouseClicked
        // TODO add your handling code here:
        bg.setVisible(false);
        registroP.setVisible(false);
        modD1.setVisible(false);
        asignarD.setVisible(false);
        eliminarD.setVisible(false);
        docentesP.setVisible(true);
        crearD1.setVisible(true);

    }//GEN-LAST:event_addDMouseClicked

    private void addDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDMouseEntered
        // TODO add your handling code here:
        crearDP1.setBackground(originalColor);
        addD.setForeground(Color.WHITE);
    }//GEN-LAST:event_addDMouseEntered

    private void addDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDMouseExited
        // TODO add your handling code here:
        crearDP1.setBackground(Color.WHITE);
        addD.setForeground(originalColor);

    }//GEN-LAST:event_addDMouseExited

    private void deleteDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDMouseEntered
        // TODO add your handling code here:
        eliminarDP1.setBackground(originalColor);
        deleteD.setForeground(Color.WHITE);
    }//GEN-LAST:event_deleteDMouseEntered

    private void deleteDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDMouseExited
        // TODO add your handling code here:
        eliminarDP1.setBackground(Color.WHITE);
        deleteD.setForeground(originalColor);
    }//GEN-LAST:event_deleteDMouseExited
    
    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void modDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDMouseClicked
        // TODO add your handling code here:
        bg.setVisible(false);
        registroP.setVisible(false);
        docentesP.setVisible(true);
        eliminarD.setVisible(false);
        crearD1.setVisible(false);
        asignarD.setVisible(false);
        modD1.setVisible(true);
    }//GEN-LAST:event_modDMouseClicked

    private void crearDP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearDP1MouseEntered
        // TODO add your handling code here:
        crearDP1.setBackground(originalColor);
        addD.setForeground(Color.WHITE);
    }//GEN-LAST:event_crearDP1MouseEntered

    private void crearDP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearDP1MouseClicked
        // TODO add your handling code here:
        bg.setVisible(false);
        registroP.setVisible(false);
        docentesP.setVisible(true);
        modD1.setVisible(false);
        eliminarD.setVisible(false);
        asignarD.setVisible(false);
        crearD1.setVisible(true);

    }//GEN-LAST:event_crearDP1MouseClicked

    private void asignDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignDMouseClicked
        // TODO add your handling code here:
        bg.setVisible(false);
        registroP.setVisible(false);
        eliminarD.setVisible(false);
        modD1.setVisible(false);
        crearD1.setVisible(false);
        docentesP.setVisible(true);
        asignarD.setVisible(true);

    }//GEN-LAST:event_asignDMouseClicked

    private void deleteDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDMouseClicked
        // TODO add your handling code here:

        bg.setVisible(false);
        registroP.setVisible(false);
        modD1.setVisible(false);
        crearD1.setVisible(false);
        asignarD.setVisible(false);
        docentesP.setVisible(true);
        eliminarD.setVisible(true);

    }//GEN-LAST:event_deleteDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("IOS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addD;
    private javax.swing.JLabel asignD;
    private javax.swing.JPanel asignarD;
    private javax.swing.JPanel asignarDP1;
    private javax.swing.JLabel badLoginTXT;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenidaTXT;
    private javax.swing.JPanel closeP;
    private javax.swing.JPanel closeP1;
    private javax.swing.JPanel closeP2;
    private javax.swing.JLabel closeTXT;
    private javax.swing.JLabel closeTXT1;
    private javax.swing.JLabel closeTXT2;
    private javax.swing.JPanel crearD1;
    private javax.swing.JPanel crearDP1;
    private javax.swing.JLabel deleteD;
    private javax.swing.JPanel docentesP;
    private javax.swing.JPanel eliminarD;
    private javax.swing.JPanel eliminarDP1;
    private javax.swing.JLabel forgotPassTXT;
    private javax.swing.JButton ingresarBT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel modD;
    private javax.swing.JPanel modD1;
    private javax.swing.JPanel modDP1;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JPanel registroP;
    private javax.swing.JLabel registrou1;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
